spring.application.name=poupa-mais-backend

server.port=8081

spring.datasource.url=jdbc:h2:mem:poupamaisdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.security.jwt.secret=0123456789012345678901234567890123456789012345678901234567890123
app.security.jwt.expiration-seconds=3600
